# Generated by Django 6.0.6 on 2026-07-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('klimafolge', models.CharField(choices=[('hitze', 'Hitze'), ('hochwasser', 'Hochwasser'), ('duerre', 'Dürre'), ('sturm', 'Sturm'), ('waldbrand', 'Waldbrand')], max_length=20)),
                ('typ', models.CharField(choices=[('naturbasiert', 'Naturbasiert'), ('baulich', 'Baulich-technisch'), ('organisatorisch', 'Organisatorisch')], max_length=20)),
                ('sektor', models.CharField(choices=[('stadt', 'Stadt & Infrastruktur'), ('landwirtschaft', 'Landwirtschaft'), ('wasser', 'Wasser'), ('gesundheit', 'Gesundheit'), ('energie', 'Energie')], max_length=20)),
                ('region', models.CharField(blank=True, max_length=200)),
                ('kosten', models.CharField(choices=[('niedrig', 'Niedrig'), ('mittel', 'Mittel'), ('hoch', 'Hoch')], max_length=10)),
                ('quelle', models.URLField(blank=True)),
            ],
        ),
    ]
