# Generated by Django 6.0.6 on 2026-07-02 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adaptations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClimateSolution',
            new_name='ClimateAdaptations',
        ),
    ]
