# Generated by Django 6.0.6 on 2026-07-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptations', '0002_rename_climatesolution_climateadaptations'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateAdaptation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('climate_impact', models.CharField(choices=[('heat', 'Extreme heat'), ('flooding', 'Flooding'), ('drought', 'Drought'), ('storm', 'Storm'), ('wildfire', 'Wildfire'), ('water_scarcity', 'Water scarcity'), ('extreme_cold', 'Extreme cold'), ('ice_and_snow', 'Ice and snow'), ('sea_level_rise', 'Sea level rise'), ('non_specific', 'Non specific')], max_length=30)),
                ('additional_impacts', models.CharField(blank=True, max_length=200)),
                ('type', models.CharField(choices=[('nature_based', 'Nature-based'), ('structural', 'Structural / technical'), ('organisational', 'Organisational')], max_length=20)),
                ('sector', models.CharField(choices=[('urban', 'Urban & infrastructure'), ('agriculture', 'Agriculture'), ('water', 'Water management'), ('health', 'Health'), ('energy', 'Energy'), ('biodiversity', 'Biodiversity protection'), ('forestry', 'Forestry'), ('tourism', 'Tourism'), ('disaster_risk', 'Disaster risk reduction'), ('non_specific', 'Non specific')], max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='ClimateAdaptations',
        ),
    ]
