# Generated by Django 6.0.6 on 2026-07-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptations', '0003_climateadaptation_delete_climateadaptations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climateadaptation',
            name='type',
            field=models.CharField(choices=[('nature_based', 'Nature-based'), ('structural', 'Structural / Technical'), ('organisational', 'Organisational')], max_length=20),
        ),
    ]
