# Generated by Django 6.0.6 on 2026-07-03 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adaptations', '0004_alter_climateadaptation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='climateadaptation',
            name='additional_impacts',
        ),
    ]
